account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import (
    RegisterView,
    Login, Account, AccountUserRequests, AboutUs, BashgahTech5
)

app_name = 'account'
urlpatterns = [
    path('', Account.as_view(), name='account-page'),
    path('requests/', AccountUserRequests.as_view(), name='account-user-requests'),

    path('register/', RegisterView.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('about-us/', AboutUs.as_view(), name='about-us'),
    path('bashgah-tech5/', BashgahTech5.as_view(), name='bashgah-tech5'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('events/', include('events.urls')),
    path('', include('core.urls')),
    path('', include('events.urls')),
    # path('account/', include('account.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    home_view,
    about_view,event_view,
    home_ex_view,
    TeammateRequestFormView,
    GymRequestFormView,
    CoachRequestFormView
)

app_name = 'core'
urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('event/', event_view, name='event'),
    path('ex/', home_ex_view, name='exhome'),
    path('teammate-request/', TeammateRequestFormView.as_view(), name='teammate-request'),
    path('gym-request/', GymRequestFormView.as_view(), name='gym-request'),
    path('coach-request/', CoachRequestFormView.as_view(), name='coach-request'),
]

templates/base/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Meta Tag-->
    <meta name="description" content="">
    <!--Meta keyword-->
    <meta name="keyword" content="">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'template_statics/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'template_statics/css/bootstrap-rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'template_statics/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'template_statics/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'template_statics/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'template_statics/css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'template_statics/css/jquery.fancybox.min.css' %}">

    <link rel="stylesheet" href="{% static 'template_statics/css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'template_statics/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'template_statics/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'template_statics/css/style.css' %}">

</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

<div class="site-wrap">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>


    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">

        <div class="container-fluid">
            <div class="d-flex align-items-center">
                <div class="site-logo mr-auto w-25">
                    <a href="{% url 'core:home' %}"><img style="width: 100px; "
                                                         src="{% static 'template_statics/pics/logo-setad.png' %}"><img
                            style="width: 120px; padding-top: 4px"
                            src="{% static 'template_statics/pics/logo-tech5.png' %}" alt="img">
                    </a></div>

                <div class="mx-auto text-center">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mx-auto d-none d-lg-block  m-0 p-0 ">
                            <li><a href="{% url 'core:home' %}" class="nav-link" style="color: #0b0b0b">خانه</a></li>
                            <li><a href="{% url 'account:bashgah-tech5' %}" class="nav-link" style="color: #0b0b0b">باشگاه
                                تکفایو</a></li>
                            {#                            <li><a href="{% url 'core:coach-request' %}" class="nav-link" style="color: #0b0b0b">درخواست مربی</a></li>#}
                            <li><a href="{% url 'account:about-us' %}" class="nav-link" style="color: #0b0b0b">درباره
                                تکفایو</a></li>
                        </ul>
                    </nav>
                </div>

                <div class="ml-auto w-25">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu site-menu-dark js-clone-nav mr-auto d-none d-lg-block m-0 p-0">
                            <li class="cta">
                                {% if request.user.is_authenticated %}
                                    <a href="{% url 'account:account-page' %}"
{#                                       class="nav-link"><span>{{ request.user.get_full_name }}</span></a>#}
                                       class="nav-link"><span>پنل کاربری</span></a>
                                {% else %}
                                    <a href="{% url 'account:login' %}" class="nav-link"><span>ورود به حساب</span></a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                                        <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right"><span
                                                class="icon-menu h3"></span></a>
                </div>
            </div>
        </div>

    </header>

    {% block intro %}

    {% endblock %}
</div>

{% block content %}

{% endblock %}


<footer class="footer-section bg-white">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h3>آدرس:</h3>
                <p>
                    کرج _ دانشگاه خوارزمی _ خانه خلاق
                </p>
                <h3>شماره تماس:</h3>
                <p style="padding-right: 123px">09393750790</p>
                <p style="padding-right: 123px">09125866638</p>
            </div>

            <div class="col-md-3 ml-auto">
                <h3>لینک ها</h3>
                <ul class="list-unstyled footer-links">
                    <li><a href="http://aran5.ir/">aran5.ir</a></li>
                    <li>
                        <a href="https://upfactor.ir/">upfactor.ir</a></li>
                    <li>
                    <li>
                        <a href="https://sarajob.ir/">sarajob.ir</a></li>
                    <li>
                </ul>
            </div>

            <div class="col-md-4">
                <h3>اشتراک</h3>
                <p>برای عضویت در خبرنامه در کادر زیر ایمیل خود را وارد کنید</p>
                <form action="#" class="footer-subscribe">
                    <div class="d-flex mb-5">
                        <input type="text" class="form-control rounded-0" placeholder="ایمیل">
                        <input type="submit" class="btn btn-primary rounded-0" value="اشتراک">
                    </div>
                </form>
            </div>

        </div>

        <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
                <div class="border-top pt-5">
                    CopyRight &copy;<script>document.write(new Date().getFullYear());</script>
                    All Rights reserved by Upfactor
                </div>
            </div>

        </div>
    </div>
</footer>


</div> <!-- .site-wrap -->

<script src="{% static 'template_statics/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'template_statics/js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'template_statics/js/jquery-ui.js' %}"></script>
<script src="{% static 'template_statics/js/popper.min.js' %}"></script>
<script src="{% static 'template_statics/js/bootstrap.min.js' %}"></script>
<script src="{% static 'template_statics/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'template_statics/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'template_statics/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'template_statics/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'template_statics/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'template_statics/js/aos.js' %}"></script>
<script src="{% static 'template_statics/js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'template_statics/js/jquery.sticky.js' %}"></script>


<script src="{% static 'template_statics/js/main.js' %}"></script>

{% block manual_js_code %}

{% endblock %}

</body>
</html>