account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import (
    RegisterView,
    Login, Account, AccountUserRequests, AboutUs, BashgahTech5
)

app_name = 'account'
urlpatterns = [
    path('', Account.as_view(), name='account-page'),
    path('requests/', AccountUserRequests.as_view(), name='account-user-requests'),

    path('register/', RegisterView.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('about-us/', AboutUs.as_view(), name='about-us'),
    path('bashgah-tech5/', BashgahTech5.as_view(), name='bashgah-tech5'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('events/', include('events.urls')),
    path('', include('core.urls')),
    path('', include('events.urls')),
    # path('account/', include('account.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    home_view,
    about_view,event_view,
    home_ex_view,
    TeammateRequestFormView,
    GymRequestFormView,
    CoachRequestFormView
)

app_name = 'core'
urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('event/', event_view, name='event'),
    path('ex/', home_ex_view, name='exhome'),
    path('teammate-request/', TeammateRequestFormView.as_view(), name='teammate-request'),
    path('gym-request/', GymRequestFormView.as_view(), name='gym-request'),
    path('coach-request/', CoachRequestFormView.as_view(), name='coach-request'),
]

events/urls.py
from django.urls import path
from . import views
from django.urls import path

urlpatterns = [
    # path('events/', views.events.as_view(), name='new-events'),
    path('events/', views.Contact_Us, name='new-events'),
]

core/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
User = get_user_model()


class Activity(models.Model):
    name = models.CharField(max_length=200, verbose_name='نام فعالیت')
    description = models.CharField(max_length=255, null=True, blank=True, verbose_name='توضیحات')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'فعالیت'
        verbose_name_plural = 'فعالیت ها'

    def __str__(self):
        return self.name


GENDER_CHOICES = (
    ('m', 'مرد'),
    ('fm', 'زن'),
    ('other', 'غیره')
)


class TeammateRequest(models.Model):
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, verbose_name='جنسیت')
    location = models.CharField(max_length=255, verbose_name='موقعیت جغرافیایی')
    activities = models.ManyToManyField(Activity, related_name='teammates', verbose_name='فعالیت های انتخاب شده')
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='teammate_requests', verbose_name='کاربر')
    description = models.TextField(null=True, blank=True, verbose_name='توضیحات')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'درخواست هم تیمی'
        verbose_name_plural = 'درخواست های هم تیمی'

    def __str__(self):
        return f"{self.user.get_full_name()} | {self.location} | {self.activities.count()} فعالیت"


class GymRequest(models.Model):
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, verbose_name='جنسیت')
    location = models.CharField(max_length=255, verbose_name='موقعیت جغرافیایی')
    activities = models.ManyToManyField(Activity, related_name='gyms', verbose_name='فعالیت های انتخاب شده')
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='gym_requests', verbose_name='کاربر'
    )
    files = models.FileField(
        upload_to='gym-request/', null=True, blank=True, verbose_name='اطلاعات مجموعه'
    )
    description = models.TextField(null=True, blank=True, verbose_name='توضیحات')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'درخواست باشگاه'
        verbose_name_plural = 'درخواست های باشگاه'

    def __str__(self):
        return f"{self.user.get_full_name()} | {self.location} | {self.activities.count()} فعالیت"


class CoachRequest(models.Model):
    TYPE_OF_TRAINING_CHOICES = (
        ('a', 'حضوری'),
        ('b', 'مجازی')
    )
    type_of_training = models.CharField(max_length=5, choices=TYPE_OF_TRAINING_CHOICES, verbose_name='نوع آموزش')
    location = models.CharField(max_length=255, verbose_name='موقعیت جغرافیایی')
    activities = models.ManyToManyField(Activity, related_name='coaches', verbose_name='فعالیت های انتخاب شده')
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='coach_requests', verbose_name='کاربر'
    )
    description = models.TextField(null=True, blank=True, verbose_name='توضیحات')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'درخواست مربی'
        verbose_name_plural = 'درخواست های مربی'

    def __str__(self):
        return f"{self.user.get_full_name()} | {self.location} | {self.activities.count()} فعالیت"

events/models.py
from django.db import models
from django.core.validators import RegexValidator
from django import forms


# Create your models here.


class ContactUs(models.Model):
    email = models.EmailField(max_length=300, verbose_name='ایمیل')
    name = models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')
    phone = models.CharField(max_length=11, default=None)

    class Meta:
        verbose_name = 'رویداد'
        verbose_name_plural = 'رویدادها'

    def __str__(self):
        return self.name

core/forms.py
from django import forms

from core.models import TeammateRequest, Activity, GymRequest, CoachRequest


class TeammateRequestForm(forms.ModelForm):
    activities = forms.ModelMultipleChoiceField(
        queryset=Activity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta:
        model = TeammateRequest
        fields = ('gender', 'location', 'activities', 'user', 'description')
        widgets = {
            'description': forms.Textarea(
                attrs={'rows': 4, 'cols': 15, 'placeholder': 'میزان مهارت خود در فعالیت های انتخاب شده را وارد کنید'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].required = False


class GymRequestForm(forms.ModelForm):
    activities = forms.ModelMultipleChoiceField(
        queryset=Activity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta:
        model = GymRequest
        fields = ('gender', 'location', 'activities', 'user', 'files', 'description')
        widgets = {
            'description': forms.Textarea(
                attrs={'rows': 4, 'cols': 15, 'placeholder': 'جنسیت، رده سنی و زمان بندی هر فعالیت را وارد کنید.'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].required = False


class CoachRequestForm(forms.ModelForm):
    activities = forms.ModelMultipleChoiceField(
        queryset=Activity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta:
        model = CoachRequest
        fields = ('type_of_training', 'location', 'activities', 'user', 'description')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4, 'cols': 15}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].required = False

events/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from django import forms
from account.models import User


class ContactusForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea, required=False, label='پیام')
    name = forms.CharField(max_length=25, required=True, label='نام و نام خانوادگی')
    email = forms.EmailField(required=True, label='ایمیل', max_length=30)
    subject = forms.CharField(required=True, max_length=25, label='موضوع')
    phone = forms.CharField(max_length=11, required=True, label='شماره تماس')

core/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.
from core.forms import TeammateRequestForm, GymRequestForm, CoachRequestForm
from core.models import TeammateRequest, GymRequest, CoachRequest


def home_view(request):
    return render(request, 'core/home.html')


def about_view(request):
    return render(request, 'core/about.html')

def event_view(request):
    return render(request, 'core/event.html')


def home_ex_view(request):
    return render(request, 'core/home_ex.html')


class TeammateRequestFormView(SuccessMessageMixin, CreateView):
    model = TeammateRequest
    template_name = 'core/teammate_request_form.html'
    form_class = TeammateRequestForm
    success_url = reverse_lazy('core:teammate-request')
    success_message = 'درخواست شما با موفقیت ارسال شد.'

    def form_valid(self, form):
        teammate_request_form = form.save(commit=False)
        teammate_request_form.user = self.request.user
        teammate_request_form.save()
        return super(TeammateRequestFormView, self).form_valid(form)


class GymRequestFormView(SuccessMessageMixin, CreateView):
    model = GymRequest
    template_name = 'core/gym_request_form.html'
    form_class = GymRequestForm
    success_url = reverse_lazy('core:gym-request')
    success_message = 'درخواست شما با موفقیت ارسال شد.'

    def form_valid(self, form):
        gym_request_form = form.save(commit=False)
        gym_request_form.user = self.request.user
        gym_request_form.save()
        return super(GymRequestFormView, self).form_valid(form)


class CoachRequestFormView(SuccessMessageMixin, CreateView):
    model = CoachRequest
    template_name = 'core/coach_request_form.html'
    form_class = CoachRequestForm
    success_url = reverse_lazy('core:coach-request')
    success_message = 'درخواست شما با موفقیت ارسال شد.'

    def form_valid(self, form):
        coach_request_form = form.save(commit=False)
        coach_request_form.user = self.request.user
        coach_request_form.save()
        return super(CoachRequestFormView, self).form_valid(form)

events/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.shortcuts import render, redirect
from .forms import ContactusForm
from config import settings
from django.core.mail import send_mail
from .models import ContactUs

# Create your views here.


class events(ListView):
    template_name = 'events.html'


def Contact_Us(request):

    sent = False
    if request.method == 'POST':
        form = ContactusForm(request.POST)
        if form.is_valid():


            cd = form.cleaned_data
            subject = cd['subject']
            name = cd['name']
            email = cd['email']
            phone = cd['phone']
            message = cd['message']

            obj = ContactUs()
            obj.name = form.cleaned_data['name']
            obj.email = form.cleaned_data['email']
            obj.phone = form.cleaned_data['phone']
            obj.save()

            msg = "name: {0}\nphone: {1}\nemail: {2}\n".format(name, phone, email, message)
            # todo : show user a success message
            send_mail(subject, msg, 'sara.adibi20000@gmail.com', ['sara.adibi20000@gmail.com', 'tech5.ir.event@gmail.com'], fail_silently=False)
            sent = True
            return render(request, 'events.html', {'form': form, sent:sent})
    form = ContactusForm()
    return render(request, 'events.html', )

core/templates/core/coach_request_form.html
{% extends 'base/_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    درخواست مربی | تیمو
{% endblock %}

{% block intro %}
    <div class="intro-section single-cover" id="home-section">

        <div class="slide-1 " style="background-image: url({% static 'template_statics/pics/img_2.jpg' %});"
             data-stellar-background-ratio="0.5">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="row justify-content-center align-items-center text-center">
                            <div class="col-lg-6">
                                <h1 data-aos="fade-up" data-aos-delay="0">فرم درخواست مربی</h1>
                                {% if not request.user.is_authenticated %}
                                    <p data-aos="fade-up" data-aos-delay="100">لطفا وارد حساب خود شوید
                                        &bullet; <a href="{% url 'account:register' %}" class="text-white">ورود به
                                            حساب</a>
                                    </p>
                                {% endif %}
                            </div>


                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-9">
                    <h3 class="text-black mb-2 text-center">اطلاعات خودرا وارد کنید</h3>
                    <p>
                        میخوای مسابقه بدی تیم نداری ؟ میخوای ورزش کنی ولی تنهایی ؟ افراد پایه ی نزدیک به خودت رو پیدا کن
                        و از ورزش کردن لذت ببر .
                    </p>

                    {% for message in messages %}
                        <div class="alert alert-info my-2">{{ message }}</div>
                    {% endfor %}

                    {% if request.user.is_authenticated %}
                        <form method="post" class="form-box border">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <label for="{{ form.type_of_training.id_for_label }}" class="text-black">نوع
                                        آموزش:</label>
                                    {{ form.type_of_training|add_class:"form-control" }}
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="id_location" class="text-black">منطقه
                                        جغرافیایی:</label>
                                    <select name="location" id="id_location" class="form-control"></select>
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="{{ form.activities.id_for_label }}" class="text-black">فعالیت
                                        ها:</label>
                                    {{ form.activities }}
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="{{ form.description.id_for_label }}" class="text-black">توضیحات:</label>
                                    {{ form.description|add_class:"form-control" }}
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary btn-pill">ارسال</button>
                                </div>
                            </div>
                        </form>
                    {% else %}
                        <div class="rounded border p-3">
                            <h6>برای مشاهده فرم ابتدا <a href="{% url 'account:login' %}">وارد حساب</a> خود شوید.</h6>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block manual_js_code %}
    <script src="{% static 'template_statics/js/select_locations.js' %}"></script>
{% endblock %}

core/templates/core/gym_request_form.html
{% extends 'base/_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    درخواست باشگاه | تیمو
{% endblock %}

{% block intro %}
    <div class="intro-section single-cover" id="home-section">

        <div class="slide-1 " style="background-image: url({% static 'template_statics/pics/img_2.jpg' %});"
             data-stellar-background-ratio="0.5">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="row justify-content-center align-items-center text-center">
                            <div class="col-lg-6">
                                <h1 data-aos="fade-up" data-aos-delay="0">فرم درخواست باشگاه</h1>
                                {% if not request.user.is_authenticated %}
                                    <p data-aos="fade-up" data-aos-delay="100">لطفا وارد حساب خود شوید
                                        &bullet; <a href="{% url 'account:register' %}" class="text-white">ورود به
                                            حساب</a>
                                    </p>
                                {% endif %}
                            </div>


                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-9">
                    <h3 class="text-black mb-2 text-center">اطلاعات خودرا وارد کنید</h3>
                    <p>
                        ورزشکاری یا تازه تصمیم به ورزش کردن گرفتی ؟ دنبال جایی میگردی که بتونی با دوستات بازی کنی و یه
                        رقابت سالم رو تجربه کنی ؟ باشگاه ها و زمین های ورزشی نزدیک به خودت رو پیدا کن و از ورزش کردن لذت
                        ببر .
                    </p>

                    {% for message in messages %}
                        <div class="alert alert-info my-2">{{ message }}</div>
                    {% endfor %}

                    {% if request.user.is_authenticated %}
                        <form method="post" class="form-box border">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <label for="{{ form.gender.id_for_label }}" class="text-black">جنسیت:</label>
                                    {{ form.gender|add_class:"form-control" }}
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="id_location" class="text-black">منطقه
                                        جغرافیایی:</label>
                                    <select name="location" id="id_location" class="form-control"></select>
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="{{ form.activities.id_for_label }}" class="text-black">فعالیت
                                        ها:</label>
                                    {{ form.activities }}
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="{{ form.files.id_for_label }}" class="text-black">تصاویر مجموعه:</label>
                                    {{ form.files|add_class:"form-control" }}
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="{{ form.description.id_for_label }}" class="text-black">توضیحات:</label>
                                    {{ form.description|add_class:"form-control" }}
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary btn-pill">ارسال</button>
                                </div>
                            </div>
                        </form>
                    {% else %}
                        <div class="rounded border p-3">
                            <h6>برای مشاهده فرم ابتدا <a href="{% url 'account:login' %}">وارد حساب</a> خود شوید.</h6>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block manual_js_code %}
    <script src="{% static 'template_statics/js/select_locations.js' %}"></script>
{% endblock %}

core/templates/core/home_ex.html
{% extends 'base/_base.html' %}
{% load static %}

{% block title %}
    صفحه اصلی | تکفایو
{% endblock %}

{% block intro %}
    <div class="intro-section" id="home-section">

        <div class="slide-1" style="background-image: url({% static 'template_statics/pics/im2.jpg' %});"
             data-stellar-background-ratio="0.5">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="row align-items-center">
                            <div class="col-lg-6 mb-4">
                                <h1 data-aos="fade-up" data-aos-delay="100">تکفایو</h1>
                                <p class="mb-4" data-aos="fade-up" data-aos-delay="200">رویداد تکرارشونده اقتصاد نسل 5</p>
                            </div>

                            <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="500">
                                <div class="form-box">
                                    <div class="border border-info rounded p-2 mt-2">
                                        <p class="font-weight-bold text-black">
                                            <a href="/events/" style=" margin-top: 1px"> ثبت نام در رویداد فریلنسر شو</a>
                                        </p>
                                        <p style="color: #545b62; font-size: 12px; margin-top: 1px">سفر قهرمانی خود اشتغالی</p>

                                    </div>
{#                                    <div class="border border-info rounded p-2 mt-2">#}
{#                                        <p class="font-weight-bold text-black">#}
{#                                            <a href="{% url 'core:gym-request' %}">درخواست باشگاه</a>#}
{#                                        </p>#}
{#                                    </div>#}
{#                                    <div class="border border-info rounded p-2 mt-2">#}
{#                                        <p class="font-weight-bold text-black">#}
{#                                            <a href="{% url 'core:coach-request' %}">درخواست مربی</a>#}
{#                                        </p>#}
{#                                    </div>#}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="site-section" id="programs-section">
        <div class="container">
            <div class="row mb-5 justify-content-center">
                <div class="col-lg-7 text-center" data-aos="fade-up" data-aos-delay="">
                    <h1 class="">فریلنسرشو | سفر قهرمانی خود اشتغالی</h1>
                </div>
            </div>
             <div class="row mb-5 align-items-center">

                    <h2 class="text-black mb-4">توضیح رویداد فریلنسرشو...</h2>


            </div>

{#            <div class="row mb-5 align-items-center">#}
{#                <div class="col-lg-7 mb-5 order-1 order-lg-2" data-aos="fade-up" data-aos-delay="100">#}
{#                    <img src="{% static 'template_statics/pics/50.jpg' %}" alt="Image"#}
{#                         class="img-fluid">#}
{#                </div>#}
{#                <div class="col-lg-4 mr-auto order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">#}
{#                    <h2 class="text-black mb-4">هم تیمیت رو پیدا کن</h2>#}
{##}
{#                    <div class="d-flex align-items-center custom-icon-wrap mb-3">#}
{#                        <span class="custom-icon-inner ml-3"><span class="icon icon-graduation-cap"></span></span>#}
{#                        <div><h3 class="m-0">درخواست هم تیمی بده</h3></div>#}
{#                    </div>#}
{#                    <div class="d-flex align-items-center custom-icon-wrap mb-3">#}
{#                        <span class="custom-icon-inner ml-3"><span class="icon icon-graduation-cap"></span></span>#}
{#                        <div><h3 class="m-0">درخواست باشگاه بده</h3></div>#}
{#                    </div>#}
{##}
{#                    <div class="d-flex align-items-center custom-icon-wrap">#}
{#                        <span class="custom-icon-inner ml-3"><span class="icon icon-university"></span></span>#}
{#                        <div><h3 class="m-0">درخواست مربی ثبت کن</h3></div>#}
{#                    </div>#}
{##}
{#                </div>#}
{#            </div>#}


{% include 'core/sites.html' %}





        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="site-section pb-0">

        <div class="future-blobs">
            <div class="blob_2">
                <img src="{% static 'template_statics/pics/blob_2.svg' %}" alt="Image">
            </div>
            <div class="blob_1">
                <img src="{% static 'template_statics/pics/blob_1.svg' %}" alt="Image">
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/teammate_request_form.html
{% extends 'base/_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    درخواست هم تیمی | تیمو
{% endblock %}

{% block intro %}
    <div class="intro-section single-cover" id="home-section">

        <div class="slide-1 " style="background-image: url({% static 'template_statics/pics/img_2.jpg' %});"
             data-stellar-background-ratio="0.5">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="row justify-content-center align-items-center text-center">
                            <div class="col-lg-6">
                                <h1 data-aos="fade-up" data-aos-delay="0">فرم درخواست هم تیم</h1>
                                {% if not request.user.is_authenticated %}
                                    <p data-aos="fade-up" data-aos-delay="100">لطفا وارد حساب خود شوید
                                        &bullet; <a href="{% url 'account:register' %}" class="text-white">ورود به
                                            حساب</a>
                                    </p>
                                {% endif %}
                            </div>


                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-9">
                    <h3 class="text-black mb-2 text-center">اطلاعات خودرا وارد کنید</h3>
                    <p>
                        میخوای مسابقه بدی تیم نداری ؟ میخوای ورزش کنی ولی تنهایی ؟ افراد پایه ی نزدیک به خودت رو پیدا کن
                        و از ورزش کردن لذت ببر .
                    </p>

                    {% for message in messages %}
                        <div class="alert alert-info my-2">{{ message }}</div>
                    {% endfor %}

                    {% if request.user.is_authenticated %}
                        <form method="post" class="form-box border">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12 mb-2">
                                    <label for="{{ form.gender.id_for_label }}" class="text-black">جنسیت:</label>
                                    {{ form.gender|add_class:"form-control" }}
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="id_location" class="text-black">منطقه
                                        جغرافیایی:</label>
                                    <select name="location" id="id_location" class="form-control"></select>
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="{{ form.activities.id_for_label }}" class="text-black">فعالیت
                                        ها:</label>
                                    {{ form.activities }}
                                </div>
                                <div class="col-12 mb-2">
                                    <label for="{{ form.description.id_for_label }}" class="text-black">توضیحات:</label>
                                    {{ form.description|add_class:"form-control" }}
                                </div>
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary btn-pill">ارسال</button>
                                </div>
                            </div>
                        </form>
                    {% else %}
                        <div class="rounded border p-3">
                            <h6>برای مشاهده فرم ابتدا <a href="{% url 'account:login' %}">وارد حساب</a> خود شوید.</h6>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block manual_js_code %}
    <script src="{% static 'template_statics/js/select_locations.js' %}"></script>
{% endblock %}